name: Deploy Azure Resources

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy with Bicep
              run: |
                  az group create --name ${{ secrets.RESOURCE_GROUP }} --location "West Europe"
                  az deployment group create \
                    --resource-group ${{ secrets.RESOURCE_GROUP }} \
                    --template-file infrastructure/main.bicep \
                    --parameters storageAccountName=photosstorage852141 functionAppName=photosFunction852141 appServicePlanName=photosPlan eventGridTopicName=photosEvents
