name: Deploy Azure Resources and Function App

on:
    push:
        branches:
            - master

jobs:
    deploy-infrastructure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Infrastructure Without Event Grid
              run: |
                  az group create --name $RESOURCE_GROUP --location "West Europe"
                  az deployment group create \
                    --resource-group $RESOURCE_GROUP \
                    --template-file infrastructure/main.bicep \
                    --parameters \
                        storageAccountName=photosstorage852141 \
                        functionAppName=photosFunction852141 \
                        appServicePlanName=photosPlan
              env:
                  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
