name: Deploy Azure Resources and Function

on:
    push:
        branches:
            - master

jobs:
    deploy-infrastructure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Infrastructure Without Event Grid
              run: |
                  az group create --name ${{ secrets.RESOURCE_GROUP }} --location "West Europe"
                  az deployment group create \
                    --resource-group ${{ secrets.RESOURCE_GROUP }} \
                    --template-file infrastructure/main.bicep \
                    --parameters storageAccountName=photosstorageunique123 functionAppName=photosFunction852141 appServicePlanName=photosPlan

    deploy-function:
        needs: deploy-infrastructure
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build Azure Function (F#)
              run: |
                  dotnet publish backend/src -c Release -o publish

            - name: Deploy Azure Function
              uses: Azure/functions-action@v1
              with:
                  app-name: photosFunction852141
                  package: ./publish
                  publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}

    deploy-eventgrid:
        needs: deploy-function
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Event Grid
              run: |
                  az deployment group create \
                    --resource-group ${{ secrets.RESOURCE_GROUP }} \
                    --template-file infrastructure/eventGrid.bicep \
                    --parameters \
                        eventGridTopicName=photosEvents \
                        functionAppUrl=https://photosFunction852141.azurewebsites.net/api/ProcessBlobCreated \
                        storageAccountId=/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.Storage/storageAccounts/photosstorageunique123
