name: Deploy Azure Resources and Function App

on:
    push:
        branches:
            - master

jobs:
    # Step 1: Deploy infrastructure (without Event Grid subscription)
    deploy-infrastructure:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy Infrastructure Without Event Grid
              run: |
                  az group create --name ${{ secrets.RESOURCE_GROUP }} --location "West Europe"
                  az deployment group create \
                    --resource-group ${{ secrets.RESOURCE_GROUP }} \
                    --template-file infrastructure/main.bicep \
                    --parameters \
                        storageAccountName=photosstorageunique123 \
                        functionAppName=photosFunction852141 \
                        appServicePlanName=photosPlan

    # Step 2: Build and deploy the Azure Function App code
    deploy-function:
        needs: deploy-infrastructure
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build Azure Function (F#)
              run: |
                  cd backend/src  # Navigate to the F# project directory
                  dotnet publish -c Release -o ../../publish  # Build and publish the function app

            - name: Deploy Azure Function
              uses: Azure/functions-action@v1
              with:
                  app-name: photosFunction852141
                  package: ./publish # Path to the published output directory
                  publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}

    # Step 3: Deploy Event Grid subscription
    deploy-eventgrid:
        needs: deploy-function
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Get Azure Subscription ID
              id: get-subscription-id
              run: |
                  SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                  echo "SUBSCRIPTION_ID=${SUBSCRIPTION_ID}" >> $GITHUB_ENV

            - name: Deploy Event Grid
              run: |
                  az deployment group create \
                    --resource-group ${{ secrets.RESOURCE_GROUP }} \
                    --template-file infrastructure/eventGrid.bicep \
                    --parameters \
                        eventGridTopicName=photosEvents \
                        functionAppUrl=https://photosFunction852141.azurewebsites.net/api/ProcessBlobCreated \
                        storageAccountId=/subscriptions/$SUBSCRIPTION_ID/resourceGroups/${
                        { secrets.RESOURCE_GROUP }} \
                        /providers/Microsoft.Storage/storageAccounts/photosstorageunique123
